# Use new container based environment
sudo: false

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - 5.6
    - 5.5
    - 5.4

# Grab the setup script and execute
before_script:
    - export PHPCS_DIR=/tmp/phpcs
    - export WPCS_DIR=/tmp/wpcs
    # Install CodeSniffer for WordPress Coding Standards checks.
    # 2.3.1 breaks PHP 5.2 on Travis due to use of Phar class.
    - git clone -b 2.3.0 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
    # Install WordPress Coding Standards.
    - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WPCS_DIR
    # Set install path for WordPress Coding Standards.
    # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $WPCS_DIR
    # After CodeSniffer install you should refresh your path.
    - phpenv rehash

script:
    # Search for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    # WordPress Coding Standards
    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    # @link https://github.com/squizlabs/PHP_CodeSniffer
    # All of the usual config flags are held in phpcs.xml
    - $PHPCS_DIR/scripts/phpcs

branches:
    only:
        - master

notifications:
    on_success: never
    on_failure: change
