# Use new container based environment
sudo: false

# Declare project language.
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

# Run test script commands.
# All commands must exit with code 0 on success. Anything else is considered failure.
script: phpunit

notifications:
    email: false
