# Use new container based environment
sudo: false

# Declare project language.
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

env:
    - WP_VERSION=latest
    - WP_VERSION=4.3
    - WP_VERSION=4.2
    - WP_VERSION=4.1
    - WP_VERSION=4.0

branches:
    only:
        - master

matrix:
    fast_finish: true
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - export PHPCS_DIR=/tmp/pphphpcs
    - export WPCS_DIR=/tmp/wpcs
    # Install CodeSniffer for WordPress Coding Standards checks.
    - git clone -b 2.3.0 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
    # Install WordPress Coding Standards.
    - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WPCS_DIR
    # Set install path for WordPress Coding Standards.
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $WPCS_DIR
    # After CodeSniffer install you should refresh your path.
    - phpenv rehash

# Run test script commands.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    # WordPress Coding Standards
    # All of the usual config flags are held in phpcs.xml
    - $PHPCS_DIR/scripts/phpcs

notifications:
    email: false
