# Use new container based environment
sudo: false

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - 5.6
    - 5.5
    - 5.4

env:
    - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

# Grab the setup script and execute
before_script:
    - git clone https://github.com/Seravo/wordpress-test-template wp-tests
    - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
    - cd wp-tests/spec && bundle exec rspec test.rb

branches:
    only:
        - master

notifications:
    on_success: never
    on_failure: change
